# Generated by Django 4.1.8 on 2023-04-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorePurchaseaddon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
                ('iccid', models.CharField(blank=True, db_column='ICCID', max_length=500, null=True)),
                ('entitytype', models.CharField(blank=True, db_column='entityType', max_length=500, null=True)),
                ('tenancyid', models.CharField(blank=True, db_column='tenancyID', max_length=500, null=True)),
                ('eventtimestamp', models.CharField(blank=True, db_column='eventTimeStamp', max_length=500, null=True)),
                ('eventname', models.CharField(blank=True, db_column='eventName', max_length=500, null=True)),
                ('eventcode', models.CharField(blank=True, db_column='eventCode', max_length=500, null=True)),
                ('transactionid', models.CharField(blank=True, db_column='TransactionId', max_length=500, null=True)),
                ('transaction', models.CharField(blank=True, max_length=500, null=True)),
                ('resourceid', models.CharField(blank=True, db_column='resourceID', max_length=500, null=True)),
                ('addonname', models.CharField(blank=True, db_column='addOnName', max_length=500, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=500, null=True)),
                ('subscriptiontype', models.CharField(blank=True, db_column='subscriptionType', max_length=500, null=True)),
                ('startdate', models.CharField(blank=True, db_column='startDate', max_length=500, null=True)),
                ('expirationdate', models.CharField(blank=True, db_column='expirationDate', max_length=500, null=True)),
                ('is_transfer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_purchaseaddon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TCL_Exception_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('iccid', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('one_liner', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
