# Generated by Django 4.1.8 on 2023-04-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcl_chedular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tcl_exception_log',
            table='TCL_Exception_Log',
        ),
    ]
